# Default config file for savethat

# save local data at this path
local_path="${PROJECT_ROOT}/data"
# prefix for this project
b2_prefix="{{ cookiecutter.project_name }}"

{% if cookiecutter.setup_backblaze.startswith('No') %}
# this will use a simulation of B2, your files will not be uploaded.
use_b2_simulation=true

# To setup Backblaze, set `use_b2_simulation = false` and fill the following:
#
# b2_key_id="{{ cookiecutter.b2_key_id }}"
# b2_key="{{ cookiecutter.b2_key }}"
# name of the B2 bucket
# b2_bucket="{{ cookiecutter.b2_bucket }}"
#
# For help on application keys, see: https://www.backblaze.com/b2/docs/application_keys.html
{% else %}
# the B2 Key
b2_key_id="{{ cookiecutter.b2_key_id }}"
b2_key="{{ cookiecutter.b2_key }}"
# name of the B2 bucket
b2_bucket="{{ cookiecutter.b2_bucket }}"
{% endif %}